"""Resume Optimizer Service coordinates the autonomous optimization loop with database persistence."""



import logging

import uuid

from typing import Optional

from datetime import datetime

from sqlalchemy.ext.asyncio import AsyncSession

from sqlalchemy.future import select



from backend.app.ai.models.candidate_profile_model import CandidateProfileModel

from backend.app.ai.repository.candidate_profile_repository import CandidateProfileRepository

from backend.app.ai.repository.optimization_repository import OptimizationRepository

from backend.app.ai.services.optimization_loop import OptimizationLoopController

from backend.app.ai.schemas.candidate_profile_schema import (

    CandidateProfile,

    ExperienceItem,

    ProjectItem,

    EducationItem

)

from backend.app.ai.schemas.job_parser_schema import JobProfile, JobParserMetadata

from backend.app.jobs.models.job_model import JobModel

from backend.app.jobs.models.analysis_model import JobAnalysisModel

from backend.app.ai.schemas.resume_optimizer_schema import (

    ResumeOptimizationRequest,

    ResumeOptimizationResponse

)

from backend.app.resume.models.resume_model import ResumeModel

from backend.app.email.models.email_model import EmailDraftModel



logger = logging.getLogger(__name__)





class ResumeOptimizerService:

    """Coordinates the retrieval of profiles, loop controller optimization, and database serialization."""



    def __init__(

        self,

        db: AsyncSession,

        loop_controller: Optional[OptimizationLoopController] = None,

        profile_repository: Optional[CandidateProfileRepository] = None

    ):

        """Initializes the service with dependency injected session, agent, and repository classes."""

        self.db = db

        self.loop_controller = loop_controller or OptimizationLoopController()

        self.profile_repository = profile_repository or CandidateProfileRepository(db)

        self.optimization_repository = OptimizationRepository(db)





    async def optimize_resume(

        self,

        user_id: uuid.UUID,

        request: ResumeOptimizationRequest

    ) -> ResumeOptimizationResponse:

        """Loads candidate and job profiles, invokes the loop controller, and persists the optimized version."""

        logger.info(f"Initiating resume optimization service call for user: {user_id}")



        # 1. Load active Candidate Profile

        db_profile = await self.profile_repository.get_active_profile(user_id)

        if not db_profile:

            logger.error(f"Active CandidateProfile not found for user: {user_id}")

            raise ValueError("Active CandidateProfile not found for this user.")



        candidate_schema = self._to_candidate_schema(db_profile)



        # 2. Load Job Profile and associated requirements analysis

        job_query = await self.db.execute(

            select(JobModel).where(JobModel.id == uuid.UUID(str(db_profile.resume_id))) # Linked via resume source relation

            # Note: in real APIs we load by request.job_profile_id, let's load by request.job_profile_id:

        )

        # Wait, let's load by request.job_profile_id to support custom targeting:

        job_query = await self.db.execute(

            select(JobModel).where(JobModel.id == uuid.UUID(str(request.job_profile_id)))

        )

        db_job = job_query.scalars().first()

        if not db_job:

            logger.error(f"JobModel not found for ID: {request.job_profile_id}")

            raise ValueError(f"Job not found for ID: {request.job_profile_id}")



        analysis_query = await self.db.execute(

            select(JobAnalysisModel).where(JobAnalysisModel.job_id == db_job.id)

        )

        db_analysis = analysis_query.scalars().first()

        if not db_analysis:

            logger.error(f"JobAnalysisModel requirements analysis not found for job: {db_job.id}")

            raise ValueError(f"Job requirements analysis not found for job: {db_job.id}")



        job_schema = self._to_job_schema(db_job, db_analysis)



        # 3. Invoke Loop Controller

        response = self.loop_controller.optimize(

            candidate=candidate_schema,

            job=job_schema,

            target_score=90.0

        )



        # Update IDs in response metadata

        response.candidate_profile_id = db_profile.id

        response.job_profile_id = db_job.id

        # 4. Persist optimization run metadata

        db_run = await self.optimization_repository.create_run(

            candidate_profile_id=db_profile.id,

            job_profile_id=db_job.id,

            initial_score=response.initial_score

        )



        # Use the database run ID as the canonical run ID

        response.run_id = f"opt-{db_run.id}"

        response.history.run_id = response.run_id



        # Persist every optimization iteration generated by the loop.

        for iteration in response.history.iterations:

            await self.optimization_repository.create_iteration(

                run_id=db_run.id,

                iteration_number=iteration.iteration_number,

                pre_score=iteration.pre_score,

                post_score=iteration.post_score,

                planning_tasks=iteration.planning_tasks,

                status=(

                    iteration.decision.value

                    if hasattr(iteration.decision, "value")

                    else str(iteration.decision)

                ),

            )



        await self.optimization_repository.create_history(

                run_id=db_run.id,

                total_iterations=response.history.total_iterations,

                optimization_log=[

                    it.model_dump(mode="json")

                    for it in response.history.iterations

                ],

            )



        # Mark the persisted run as completed with final score and status

        await self.optimization_repository.update_run_completion(

            run_id=db_run.id,

            final_score=response.final_score,

            status=response.status.value if hasattr(response.status, "value") else str(response.status),

        )



        # 5. Persist optimization results as a tailored (inactive) resume version

        # Extract optimized profile from controller response

        optimized_profile = response.history.iterations[-1].decision == "ACCEPTED" if response.history.iterations else False



        # Determine the profile to save (the optimized one from the response or original if failed)

        # Note: best_profile is returned in response.history and changes, let's reconstruct the final optimized CandidateProfile

        final_profile = candidate_schema.model_copy(deep=True)

        # Apply summary and skill changes if present

        for diff in response.changes:

            if diff.section_name == "summary":

                final_profile.professional_summary = diff.optimized_text

            elif diff.section_name == "skills":

                final_profile.skills = [s.strip() for s in diff.optimized_text.split(",") if s.strip()]

            elif diff.section_name.startswith("experience_"):

                # E.g. experience_1_description

                try:

                    idx = int(diff.section_name.split("_")[1]) - 1

                    if idx < len(final_profile.experience):

                        final_profile.experience[idx].description = diff.optimized_text

                except (ValueError, IndexError):

                    pass



        # Create tailored version metadata record (is_active = False to preserve master resume)

        await self.profile_repository.create_profile(

            user_id=user_id,

            resume_id=db_profile.resume_id,

            profile=final_profile,

            is_active=False

        )



        # Commit database transaction

        await self.db.flush()

        logger.info(f"Persisted optimized resume version successfully for user: {user_id}")



        # Phase 7: Recruiter/Application contact information check

        recruiter_email = db_job.recruiter_email

        if not recruiter_email and db_analysis.metadata_json:

            recruiter_email = db_analysis.metadata_json.get("recruiter_email")



        email_draft_id = None

        import re

        import os

        email_regex = r"^[\w\.-]+@[\w\.-]+\.\w+$"

        if recruiter_email and re.match(email_regex, str(recruiter_email).strip()):

            recruiter_email = str(recruiter_email).strip()



            # Compile optimized resume file path

            clean_company = re.sub(r"\s+", "", db_job.company_name or "Company")

            clean_role = re.sub(r"\s+", "", db_job.job_title or "Role")

            date_str = datetime.utcnow().strftime("%Y-%m-%d")

            filename = f"{user_id}_{clean_role}_{clean_company}_{date_str}.pdf"



            # Ensure target storage directory exists

            storage_path = os.path.join(

                os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),

                "storage"

            )

            os.makedirs(storage_path, exist_ok=True)

            optimized_resume_path = os.path.join(storage_path, filename)



            # Retrieve master resume from db

            resume_query = await self.db.execute(

                select(ResumeModel).where(ResumeModel.id == db_profile.resume_id)

            )

            db_resume = resume_query.scalars().first()



            # Mock PDF generation by copying physical file

            if db_resume and db_resume.file_path and os.path.exists(db_resume.file_path):

                import shutil

                shutil.copy2(db_resume.file_path, optimized_resume_path)

            else:

                with open(optimized_resume_path, "w") as f:

                    f.write(f"Tailored Summary: {final_profile.professional_summary}\nSkills: {', '.join(final_profile.skills)}")



            # Generate personalized email draft body & subject

            subject = f"Application: {db_job.job_title} at {db_job.company_name}"

            candidate_name = db_profile.full_name or "Candidate"

            body = (

                f"Dear Hiring Team,\n\n"

                f"I hope this message finds you well.\n\n"

                f"I am writing to express my strong interest in the {db_job.job_title} position at {db_job.company_name}. "

                f"With my background in software engineering, technical skills in {', '.join(final_profile.skills[:5])}, "

                f"and professional experience, I am confident in my ability to make a meaningful contribution to your team.\n\n"

                f"Please find my tailored resume attached for your consideration. I would welcome the opportunity to discuss "

                f"how my skills align with your requirements.\n\n"

                f"Best regards,\n"

                f"{candidate_name}"

            )



            # Create draft record and flush to database

            draft = EmailDraftModel(

                id=uuid.uuid4(),

                user_id=user_id,

                recipient_email=recruiter_email,

                recipient_name=db_job.company_name or "Hiring Team",

                subject=subject,

                body=body,

                attachment_path=optimized_resume_path

            )

            self.db.add(draft)

            await self.db.flush()

            email_draft_id = draft.id



        response.email_draft_id = email_draft_id



        return response



    def _to_candidate_schema(self, model: CandidateProfileModel) -> CandidateProfile:

        """Maps CandidateProfileModel database record to CandidateProfile domain schema."""

        return CandidateProfile(

            full_name=model.full_name,

            email=model.email,

            phone=model.phone,

            linkedin_url=model.linkedin_url,

            github_url=model.github_url,

            professional_summary=model.professional_summary,

            skills=model.skills_json or [],

            experience=[ExperienceItem(**exp) for exp in (model.experience_json or [])],

            projects=[ProjectItem(**proj) for proj in (model.projects_json or [])],

            education=[EducationItem(**edu) for edu in (model.education_json or [])],

            certifications=model.certifications_json or []

        )



    def _to_job_schema(self, job: JobModel, analysis: JobAnalysisModel) -> JobProfile:

        """Maps JobModel and JobAnalysisModel database records to JobProfile domain schema."""

        metadata_json = analysis.metadata_json or {}

        skills_json = analysis.skills_json or []



        required_skills = []

        preferred_skills = []

        for s in skills_json:

            name = s.get("name")

            importance = s.get("importance", "high")

            if importance == "high":

                required_skills.append(name)

            else:

                preferred_skills.append(name)



        return JobProfile(

            company_name=job.company_name,

            job_title=job.job_title,

            experience_required=metadata_json.get("experience_required", ""),

            education_required=metadata_json.get("education_requirements", ""),

            required_skills=required_skills,

            preferred_skills=preferred_skills,

            responsibilities=analysis.responsibilities_json or [],

            qualifications=analysis.qualifications_json or [],

            original_jd=job.description,

            source_type=job.source_type,

            metadata=JobParserMetadata(

                parsed_at=job.created_at.isoformat() if job.created_at else datetime.utcnow().isoformat(),

                character_count=len(job.description or "")

            )

        )
