# backend/app/resume/api/optimization_routes.py
# FastAPI routes exposing endpoints for triggering resume matching, tailors passes & downloading compiled PDFs

import uuid
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List
from backend.app.database.session import get_async_db
from backend.app.auth.api.routes import get_current_active_user
from backend.app.auth.schemas.auth_schema import UserResponse
from backend.app.resume.repository.resume_repository import ResumeRepository
from backend.app.jobs.repository.analysis_repository import JobAnalysisRepository
from backend.app.resume.repository.optimization_repository import ResumeOptimizationRepository
from backend.app.resume.services.optimization_service import ResumeOptimizationService
from backend.app.resume.schemas.optimization_schema import (
    ResumeOptimizeRequest, 
    ResumeOptimizationResponse
)
from backend.app.shared.exceptions import BaseAppException

router = APIRouter(prefix="/resume/optimize", tags=["Resume Optimization"])

def get_optimization_service(db: AsyncSession = Depends(get_async_db)) -> ResumeOptimizationService:
    """Dependency resolver returning initialized ResumeOptimizationService instance."""
    opt_repo = ResumeOptimizationRepository(db)
    resume_repo = ResumeRepository(db)
    # Instantiate job analysis repo using the same DB session connection
    analysis_repo = JobAnalysisRepository(db)
    
    # Target storage volume folder
    storage_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "storage")
    return ResumeOptimizationService(opt_repo, resume_repo, analysis_repo, storage_path=storage_path)

# Import os for folder resolutions
import os


@router.post("", response_model=ResumeOptimizationResponse, status_code=status.HTTP_201_CREATED)
async def optimize_resume(
    payload: ResumeOptimizeRequest,
    current_user: UserResponse = Depends(get_current_active_user),
    service: ResumeOptimizationService = Depends(get_optimization_service)
):
    """Trigger AI matching and optimization loop to tailor the master resume for a job posting."""
    try:
        return await service.optimize_resume(current_user.id, payload.job_analysis_id)
    except BaseAppException as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get("/history", response_model=List[ResumeOptimizationResponse])
async def list_optimizations(
    current_user: UserResponse = Depends(get_current_active_user),
    service: ResumeOptimizationService = Depends(get_optimization_service)
):
    """List all optimization reports previously generated by the current user."""
    return await service.list_user_optimizations(current_user.id)


@router.get("/{id}", response_model=ResumeOptimizationResponse)
async def get_optimization(
    id: uuid.UUID,
    current_user: UserResponse = Depends(get_current_active_user),
    service: ResumeOptimizationService = Depends(get_optimization_service)
):
    """Retrieve details for a specific optimization report."""
    try:
        return await service.get_optimization_details(current_user.id, id)
    except BaseAppException as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=e.message)


@router.get("/report/{id}")
async def get_report(
    id: uuid.UUID,
    current_user: UserResponse = Depends(get_current_active_user),
    service: ResumeOptimizationService = Depends(get_optimization_service)
):
    """Retrieve readable match audits and recommendation summaries."""
    try:
        return await service.get_optimization_report(current_user.id, id)
    except BaseAppException as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=e.message)


@router.get("/download/{id}")
async def download_optimized(
    id: uuid.UUID,
    current_user: UserResponse = Depends(get_current_active_user),
    service: ResumeOptimizationService = Depends(get_optimization_service)
):
    """Download the optimized PDF resume file."""
    try:
        file_path, filename = await service.download_optimized_resume(current_user.id, id)
        return FileResponse(
            path=file_path,
            filename=filename,
            media_type="application/pdf"
        )
    except BaseAppException as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=e.message)
